### ISSUE TITLE
Jayway JsonPath library Error

### ISSUE THREAD

**Issue by davidromero** [spring-guides/gs-rest-hateoas#29]
Following the Guide and adding the JSON library to `pom.xml` I got the following error
```

Caused by: java.lang.NoClassDefFoundError: com/jayway/jsonpath/PathNotFoundException
	at org.springframework.hateoas.mediatype.hal.HalMediaTypeConfiguration.halLinkDisocoverer(HalMediaTypeConfiguration.java:62) ~[spring-hateoas-1.3.2.jar!/:1.3.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_302]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_302]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_302]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_302]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.8.jar!/:5.3.8]
	... 28 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.jayway.jsonpath.PathNotFoundException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382) ~[na:1.8.0_302]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_302]
	at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:151) ~[rest-hateoas-complete-0.0.1-SNAPSHOT.jar:0.0.1-SNAPSHOT]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_302]
	... 34 common frames omitted
```
Not using the library outputs no error.

Why it works without the library, i don't know. Just to make it more clear to newcomers.

Thanks!

**Comment by davidromero** [comment]
I found why it works, the dependency 
```
	<dependency>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-hateoas</artifactId>
	</dependency>
```

Includes it.

**Comment by WuRoc** [comment]
you can delete  
<dependency>
			<groupId>com.jayway.jsonpath</groupId>
			<artifactId>json-path</artifactId>
			<scope>test</scope>
		</dependency>

**Comment by goldman7911** [comment]
Remove scope test from json-path dependency. 

```
<dependency>
			<groupId>com.jayway.jsonpath</groupId>
			<artifactId>json-path</artifactId>
			<!-- <scope>test</scope> -->
</dependency>
```

https://stackoverflow.com/a/69335677/2952510

**Comment by Buzzardo** [comment]
We have simplified all of that by modifying the Spring Rest HATEOAS starter. That let us remove all mention of Jayway.
